name: 'Claude Code OAuth Login'
description: 'Authenticate with Claude Code using OAuth 2.0 flow'
author: 'Guillaume Raille <guillaume.raille@gmail.com>'
branding:
  icon: 'log-in'
  color: 'orange'

permissions:
  actions: write  # Required for cache management (create/delete cache entries)
  contents: read  # Required for basic repository access

inputs:
  code:
    description: 'Authorization code from Claude (leave empty for step 1)'
    required: false
    default: ''

outputs:
  success:
    description: 'Whether the OAuth login was successful'
    value: ${{ steps.oauth.outputs.success }}
  expires_at:
    description: 'Token expiration timestamp (milliseconds)'
    value: ${{ steps.oauth.outputs.expires_at }}

runs:
  using: 'composite'
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: 1.2.17

    - name: Install Dependencies
      shell: bash
      run: |
        cd ${GITHUB_ACTION_PATH}
        bun install

    - name: Restore OAuth State
      uses: actions/cache/restore@v4
      with:
        path: ${{ github.action_path }}/claude_oauth_state.json
        key: claude-oauth-state

    - name: Restore OAuth Credentials
      uses: actions/cache/restore@v4
      with:
        path: ${{ github.action_path }}/credentials.json
        key: claude-oauth-credentials

    - name: Run OAuth Flow
      id: oauth
      shell: bash
      run: |
        cd ${GITHUB_ACTION_PATH}
        if [ -z "${{ inputs.code }}" ]; then
          echo "🔗 Generating OAuth Login URL..."
          
          # Clear any existing state file from cache
          rm -f claude_oauth_state.json
          
          # Generate the login URL
          LOGIN_URL=$(bun run index.ts)
          
          # Create beautiful GitHub Step Summary
          echo "" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "╔══════════════════════════════════════════════════════════════════════════╗" >> $GITHUB_STEP_SUMMARY
          echo "║                                                                          ║" >> $GITHUB_STEP_SUMMARY
          echo "║                        ✨ Claude Code OAuth (by @grll) ✨                ║" >> $GITHUB_STEP_SUMMARY
          echo "║                                                                          ║" >> $GITHUB_STEP_SUMMARY
          echo "╚══════════════════════════════════════════════════════════════════════════╝" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "     ░██████╗░  ░██████╗░  ░██╗░░░░░  ░██╗░░░░░" >> $GITHUB_STEP_SUMMARY
          echo "     ██╔════╝░  ░██╔══██╗  ░██║░░░░░  ░██║░░░░░" >> $GITHUB_STEP_SUMMARY
          echo "     ██║░░██╗░  ░██████╔╝  ░██║░░░░░  ░██║░░░░░" >> $GITHUB_STEP_SUMMARY
          echo "     ██║░░╚██╗  ░██╔══██╗  ░██║░░░░░  ░██║░░░░░" >> $GITHUB_STEP_SUMMARY
          echo "     ╚██████╔╝  ░██║░░██║  ░███████╗  ░███████╗" >> $GITHUB_STEP_SUMMARY
          echo "     ░╚═════╝░  ░╚═╝░░╚═╝  ░╚══════╝  ░╚══════╝" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "   ─────────────────────────────────────────────────────────────────────" >> $GITHUB_STEP_SUMMARY
          echo "                       【 STEP 1: Generate Login URL 】" >> $GITHUB_STEP_SUMMARY
          echo "   ─────────────────────────────────────────────────────────────────────" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "## 🚀 OAuth URL Generated Successfully!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 🌐 Your Login URL" >> $GITHUB_STEP_SUMMARY
          echo "[$LOGIN_URL]($LOGIN_URL)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 📋 Next Steps" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Step | Action | Description |" >> $GITHUB_STEP_SUMMARY
          echo "|------|--------|-------------|" >> $GITHUB_STEP_SUMMARY
          echo "| 1️⃣ | **Click URL** | Open the login URL above in your browser |" >> $GITHUB_STEP_SUMMARY
          echo "| 2️⃣ | **Sign In** | Authenticate with Claude and authorize the application |" >> $GITHUB_STEP_SUMMARY
          echo "| 3️⃣ | **Copy Code** | From the callback URL: \`https://console.anthropic.com/oauth/code/callback?code=YOUR_CODE\` |" >> $GITHUB_STEP_SUMMARY
          echo "| 4️⃣ | **Run Step 2** | Come back here and run the workflow again with your code |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 🔄 Ready for Step 2!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "> **Next:** Go to **Actions** → **Claude Code OAuth Login** → **Run workflow**" >> $GITHUB_STEP_SUMMARY
          echo "> Paste your authorization code in the \`code\` input field and click **Run workflow**" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "---" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "┌─────────────────────────────────────────────────────────────────────┐" >> $GITHUB_STEP_SUMMARY
          echo "│                    🎯 STEP 1 COMPLETE - AWAITING CODE               │" >> $GITHUB_STEP_SUMMARY
          echo "└─────────────────────────────────────────────────────────────────────┘" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          
          echo "✅ Step 1 Complete - Login URL generated and displayed in summary"
          echo "success=pending" >> $GITHUB_OUTPUT
        else
          echo "🔐 Exchanging authorization code for tokens..."
          
          # Clear any existing credentials file from cache
          rm -f credentials.json
          
          # Exchange the code for tokens and capture outputs
          if bun run index.ts "${{ inputs.code }}"; then
            # Success case
            echo "" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            echo "╔══════════════════════════════════════════════════════════════════════════╗" >> $GITHUB_STEP_SUMMARY
            echo "║                                                                          ║" >> $GITHUB_STEP_SUMMARY
            echo "║                        ✨ Claude Code OAuth (by @grll) ✨                ║" >> $GITHUB_STEP_SUMMARY
            echo "║                                                                          ║" >> $GITHUB_STEP_SUMMARY
            echo "╚══════════════════════════════════════════════════════════════════════════╝" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "     ░██████╗░  ░██████╗░  ░██╗░░░░░  ░██╗░░░░░" >> $GITHUB_STEP_SUMMARY
            echo "     ██╔════╝░  ░██╔══██╗  ░██║░░░░░  ░██║░░░░░" >> $GITHUB_STEP_SUMMARY
            echo "     ██║░░██╗░  ░██████╔╝  ░██║░░░░░  ░██║░░░░░" >> $GITHUB_STEP_SUMMARY
            echo "     ██║░░╚██╗  ░██╔══██╗  ░██║░░░░░  ░██║░░░░░" >> $GITHUB_STEP_SUMMARY
            echo "     ╚██████╔╝  ░██║░░██║  ░███████╗  ░███████╗" >> $GITHUB_STEP_SUMMARY
            echo "     ░╚═════╝░  ░╚═╝░░╚═╝  ░╚══════╝  ░╚══════╝" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "   ─────────────────────────────────────────────────────────────────────" >> $GITHUB_STEP_SUMMARY
            echo "                         【 STEP 2: OAuth Complete! 】" >> $GITHUB_STEP_SUMMARY
            echo "   ─────────────────────────────────────────────────────────────────────" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "## 🎉 Authentication Successful!" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "### ✅ OAuth Flow Complete" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "Your Claude Code credentials have been successfully generated and saved!" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "### 📁 Generated Files" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "| File | Description | Status |" >> $GITHUB_STEP_SUMMARY
            echo "|------|-------------|--------|" >> $GITHUB_STEP_SUMMARY
            echo "| \`credentials.json\` | OAuth access & refresh tokens | ✅ Created & Cached |" >> $GITHUB_STEP_SUMMARY
            echo "| \`claude_oauth_state.json\` | Temporary state file | 🗑️ Cleaned up |" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "### 💾 Cached for Reuse" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "The \`credentials.json\` file has been cached with key \`claude-oauth-credentials\` and can be reused by other workflows in this repository." >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`yaml" >> $GITHUB_STEP_SUMMARY
            echo "- name: Restore Claude Credentials" >> $GITHUB_STEP_SUMMARY
            echo "  uses: actions/cache@v4" >> $GITHUB_STEP_SUMMARY
            echo "  with:" >> $GITHUB_STEP_SUMMARY
            echo "    path: credentials.json" >> $GITHUB_STEP_SUMMARY
            echo "    key: claude-oauth-credentials" >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "### 🚀 What's Next?" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "You can now use these credentials with Claude Code CLI or other tools that support the OAuth flow." >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "---" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            echo "┌─────────────────────────────────────────────────────────────────────┐" >> $GITHUB_STEP_SUMMARY
            echo "│                       🎯 AUTHENTICATION COMPLETE!                   │" >> $GITHUB_STEP_SUMMARY
            echo "│                         Ready to use Claude Code                    │" >> $GITHUB_STEP_SUMMARY
            echo "└─────────────────────────────────────────────────────────────────────┘" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            
            echo "✅ Step 2 Complete - OAuth authentication successful!"
            echo "success=true" >> $GITHUB_OUTPUT
          else
            # Failure case
            echo "" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            echo "╔══════════════════════════════════════════════════════════════════════════╗" >> $GITHUB_STEP_SUMMARY
            echo "║                                                                          ║" >> $GITHUB_STEP_SUMMARY
            echo "║                        ⚠️  Claude Code OAuth (by @grll) ⚠️               ║" >> $GITHUB_STEP_SUMMARY
            echo "║                                                                          ║" >> $GITHUB_STEP_SUMMARY
            echo "╚══════════════════════════════════════════════════════════════════════════╝" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "     ░██████╗░  ░██████╗░  ░██╗░░░░░  ░██╗░░░░░" >> $GITHUB_STEP_SUMMARY
            echo "     ██╔════╝░  ░██╔══██╗  ░██║░░░░░  ░██║░░░░░" >> $GITHUB_STEP_SUMMARY
            echo "     ██║░░██╗░  ░██████╔╝  ░██║░░░░░  ░██║░░░░░" >> $GITHUB_STEP_SUMMARY
            echo "     ██║░░╚██╗  ░██╔══██╗  ░██║░░░░░  ░██║░░░░░" >> $GITHUB_STEP_SUMMARY
            echo "     ╚██████╔╝  ░██║░░██║  ░███████╗  ░███████╗" >> $GITHUB_STEP_SUMMARY
            echo "     ░╚═════╝░  ░╚═╝░░╚═╝  ░╚══════╝  ░╚══════╝" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "   ─────────────────────────────────────────────────────────────────────" >> $GITHUB_STEP_SUMMARY
            echo "                       【 STEP 2: Authentication Failed 】" >> $GITHUB_STEP_SUMMARY
            echo "   ─────────────────────────────────────────────────────────────────────" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "## ❌ Authentication Failed" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "### 🔍 Possible Issues" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "| Issue | Solution |" >> $GITHUB_STEP_SUMMARY
            echo "|-------|----------|" >> $GITHUB_STEP_SUMMARY
            echo "| **Expired State** | Run Step 1 again to generate a new login URL |" >> $GITHUB_STEP_SUMMARY
            echo "| **Invalid Code** | Double-check the authorization code from the callback URL |" >> $GITHUB_STEP_SUMMARY
            echo "| **Network Error** | Check your internet connection and try again |" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "### 🔄 Try Again" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "1. Go back to **Actions** → **Claude Code OAuth Login** → **Run workflow**" >> $GITHUB_STEP_SUMMARY
            echo "2. Leave the \`code\` field **empty** to restart from Step 1" >> $GITHUB_STEP_SUMMARY
            echo "3. Follow the authentication flow again" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "---" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            echo "┌─────────────────────────────────────────────────────────────────────┐" >> $GITHUB_STEP_SUMMARY
            echo "│                     ⚠️  AUTHENTICATION FAILED                       │" >> $GITHUB_STEP_SUMMARY
            echo "│                        Please try again                             │" >> $GITHUB_STEP_SUMMARY
            echo "└─────────────────────────────────────────────────────────────────────┘" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            
            echo "❌ Step 2 Failed - Please check the summary for troubleshooting steps"
            echo "success=false" >> $GITHUB_OUTPUT
          fi
        fi
      env:
        MASK_CODE: ${{ inputs.code != '' && '***REDACTED***' || 'Not provided' }}

    - name: Delete Old OAuth State Cache
      shell: bash
      run: |
        if gh cache list --repo ${{ github.repository }} --key claude-oauth-state | grep -q claude-oauth-state; then
          gh cache delete claude-oauth-state --repo ${{ github.repository }}
        fi
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Save OAuth State
      if: inputs.code == ''
      uses: actions/cache/save@v4
      with:
        path: ${{ github.action_path }}/claude_oauth_state.json
        key: claude-oauth-state

    - name: Delete Old OAuth Credentials Cache
      if: inputs.code != '' && steps.oauth.outputs.success == 'true'
      shell: bash
      run: |
        if gh cache list --repo ${{ github.repository }} --key claude-oauth-credentials | grep -q claude-oauth-credentials; then
          gh cache delete claude-oauth-credentials --repo ${{ github.repository }}
        fi
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Save OAuth Credentials
      if: inputs.code != '' && steps.oauth.outputs.success == 'true'
      uses: actions/cache/save@v4
      with:
        path: ${{ github.action_path }}/credentials.json
        key: claude-oauth-credentials
